/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProvidersGetResponse}
 */
export function createProvidersGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProvidersGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoProvidersGetResponse(providersGetResponse: Partial<ProvidersGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { providersGetResponse.data = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
export interface ProvidersGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: string[];
}
/**
 * Builds and executes requests for operations under /providers.json
 */
export interface ProvidersJsonRequestBuilder extends BaseRequestBuilder<ProvidersJsonRequestBuilder> {
    /**
     * List all the providers in the directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProvidersGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProvidersGetResponse | undefined>;
    /**
     * List all the providers in the directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeProvidersGetResponse(writer: SerializationWriter, providersGetResponse: Partial<ProvidersGetResponse> | undefined = {}) : void {
    writer.writeCollectionOfPrimitiveValues<string>("data", providersGetResponse.data);
    writer.writeAdditionalData(providersGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ProvidersJsonRequestBuilderUriTemplate = "{+baseurl}/providers.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProvidersJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProvidersJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createProvidersGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
