/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createAPIFromDiscriminatorValue, type API } from '../../../models/';
import { type WithApiJsonItemRequestBuilder, WithApiJsonItemRequestBuilderRequestsMetadata } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /specs/{provider}/{apiJson-id}
 */
export interface ApiJsonItemRequestBuilder extends BaseRequestBuilder<ApiJsonItemRequestBuilder> {
    /**
     * Gets an item from the graphtypescriptv4.utilities.specs.item.item.item collection
     * @param apiJson Unique identifier of the item
     * @returns {WithApiJsonItemRequestBuilder}
     */
     byApiJson(apiJson: string) : WithApiJsonItemRequestBuilder;
    /**
     * Returns the API entry for one specific version of an API where there is no serviceName.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<API>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<API | undefined>;
    /**
     * Returns the API entry for one specific version of an API where there is no serviceName.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ApiJsonItemRequestBuilderUriTemplate = "{+baseurl}/specs/{provider}/{apiJson%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiJsonItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiJsonItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byApiJson: {
        requestsMetadata: WithApiJsonItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["api"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ApiJsonItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ApiJsonItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
