/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createAPIsFromDiscriminatorValue, type APIs } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /list.json
 */
export interface ListJsonRequestBuilder extends BaseRequestBuilder<ListJsonRequestBuilder> {
    /**
     * List all APIs in the directory.Returns links to the OpenAPI definitions for each API in the directory.If API exist in multiple versions `preferred` one is explicitly marked.Some basic info from the OpenAPI definition is cached inside each object.This allows you to generate some simple views without needing to fetch the OpenAPI definition for each API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<APIs>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<APIs | undefined>;
    /**
     * List all APIs in the directory.Returns links to the OpenAPI definitions for each API in the directory.If API exist in multiple versions `preferred` one is explicitly marked.Some basic info from the OpenAPI definition is cached inside each object.This allows you to generate some simple views without needing to fetch the OpenAPI definition for each API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ListJsonRequestBuilderUriTemplate = "{+baseurl}/list.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const ListJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ListJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
