/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createAPIsFromDiscriminatorValue, type APIs } from '../models/';
import { ServicesJsonRequestBuilderRequestsMetadata, type ServicesJsonRequestBuilder } from './servicesJson/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /{provider-id}
 */
export interface ProviderItemRequestBuilder extends BaseRequestBuilder<ProviderItemRequestBuilder> {
    /**
     * The servicesJson property
     */
    get servicesJson(): ServicesJsonRequestBuilder;
    /**
     * List all APIs in the directory for a particular providerNameReturns links to the individual API entry for each API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<APIs>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<APIs | undefined>;
    /**
     * List all APIs in the directory for a particular providerNameReturns links to the individual API entry for each API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProviderItemRequestBuilderUriTemplate = "{+baseurl}/{provider%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProviderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ProviderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    servicesJson: {
        requestsMetadata: ServicesJsonRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProviderItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProviderItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
