/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6.4/userguide/multi_project_builds.html
 */

rootProject.name = "javaclient"
include("app", "list", "utilities")
include(":components:abstractions")
project(":components:abstractions").projectDir = file("kiota-java/components/abstractions")
include(":components:http")
project(":components:http").projectDir = file("kiota-java/components/http/okHttp")
include(":components:serialization:json")
project(":components:serialization:json").projectDir = file("kiota-java/components/serialization/json")
include(":components:serialization:text")
project(":components:serialization:text").projectDir = file("kiota-java/components/serialization/text")
include(":components:serialization:form")
project(":components:serialization:form").projectDir = file("kiota-java/components/serialization/form")
include(":components:serialization:multipart")
project(":components:serialization:multipart").projectDir = file("kiota-java/components/serialization/multipart")