/*
 * This file was generated by the Gradle 'init' task.
 */

repositories {
    mavenCentral()
}

plugins {
    id("javaclient.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("jakarta.annotation:jakarta.annotation-api:2.1.1")
    implementation(project(":utilities"))
    implementation(project(":components:abstractions"))
    implementation(project(":components:http"))
    implementation(project(":components:serialization:json"))
    implementation(project(":components:serialization:text"))
    implementation(project(":components:serialization:form"))
    implementation(project(":components:serialization:multipart"))
}

application {
    // Define the main class for the application.
    mainClass.set("javaclient.app.App")
}
